// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoUJPSG3OhCY9owLcnbCYk3zkajDN6InA',
    appId: '1:321357439192:web:6521cea3f08e8cde2177ad',
    messagingSenderId: '321357439192',
    projectId: 'ofitone-c9783',
    authDomain: 'ofitone-c9783.firebaseapp.com',
    storageBucket: 'ofitone-c9783.appspot.com',
    measurementId: 'G-SFSLDN97G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFt-QSqCNM2aM74VR-IX500HGBSi8HjE',
    appId: '1:321357439192:android:dbaffd1bdbbb522f2177ad',
    messagingSenderId: '321357439192',
    projectId: 'ofitone-c9783',
    storageBucket: 'ofitone-c9783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ5TzYpDHlq-cVfjtcS2zcVPFnEreed8o',
    appId: '1:321357439192:ios:8b16e367e90eea842177ad',
    messagingSenderId: '321357439192',
    projectId: 'ofitone-c9783',
    storageBucket: 'ofitone-c9783.appspot.com',
    iosBundleId: 'com.ofitsoft.ofitone1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ5TzYpDHlq-cVfjtcS2zcVPFnEreed8o',
    appId: '1:321357439192:ios:1ddf36182ad218222177ad',
    messagingSenderId: '321357439192',
    projectId: 'ofitone-c9783',
    storageBucket: 'ofitone-c9783.appspot.com',
    iosBundleId: 'com.ofitsoft.diary.diaryMobile.RunnerTests',
  );
}
