class ApiParameterConst{
  ///File chua text json ma server tra ve
  static const String searchOption= "SearchOption";
  static const String currentPage= "CurrentPage";
  static const String pageSize= "PageSize";
  static const String objEasy= "ObjEasy";
  static const String cateID= "CateID";
  static const String textSearch= "TextSearch";
  static const String objAdv= "ObjAdv";
  static const String orgGUID= "OrgGUID";
  static const String delType= "DelType";
  static const String userName= "UserName";
  static const String password= "Password";
  static const String langID= "LangID";
  static const String socialAccessToken= "SocialAccessToken";
  static const String socialID= "SocialID";
  static const String socialSource= "SocialSource";
  static const String accessToken= "AccessToken";
  static const String otp= "OTP";
  static const String refreshToken= "RefreshToken";
  static const String user= "User";
  static const String fullName= "FullName";
  static const String listORG= "ListORG";
  static const String orgCode= "OrgCode";
  static const String orgName= "OrgName";
  static const String isTotalTax= "IsTotalTax";
  static const String isTotalDiscount= "IsTotalDiscount";
  static const String isDiscountBeforeTax= "IsDiscountBeforeTax";
  static const String listBankInfos= "ListBankInfos";
  static const String bankAccount= "BankAccount";
  static const String bankName= "BankName";
  static const String isPrimary= "IsPrimary";
  static const String storeGUID= "StoreGUID";
  static const String storeName= "StoreName";
  static const String storeCode= "StoreCode";
  static const String objectGUID= "ObjectGUID";
  static const String objectName= "ObjectName";
  static const String objectNameDisplay= "ObjectNameDisplay";
  static const String taxCode= "TaxCode";
  static const String companyName= "CompanyName";
  static const String address= "Address";
  static const String phone= "Phone";
  static const String mobile= "Mobile";
  static const String email= "Email";
  static const String website= "Website";
  static const String contactName= "ContactName";
  static const String note= "Note";
  static const String empGUID= "EmpGUID";
  static const String salaryDetailGUID = "SalaryDetailGUID";
  static const String empName= "EmpName";
  static const String empFullName= "EmpFullName";
  static const String empCode= "EmpCode";
  static const String empBirthday= "EmpBirthday";
  static const String empGender= "EmpGender";
  static const String genderName= "GenderName";
  static const String refTypeGUID= "RefTypeGUID";
  static const String refTypeCode= "RefTypeCode";
  static const String refTypeName= "RefTypeName";
  static const String warehouseGUID= "WarehouseGUID";
  static const String warehouseCode= "WarehouseCode";
  static const String warehouseName= "WarehouseName";
  static const String warehouseAddress= "WarehouseAddress";
  static const String paymentTermGUID= "PaymentTermGUID";
  static const String paymentTermName= "PaymentTermName";
  static const String itemTypeGUID= "ItemTypeGUID";
  static const String itemTypeName= "ItemTypeName";
  static const String parentGUID= "ParentGUID";
  static const String unitGUID= "UnitGUID";
  static const String unitName= "UnitName";
  static const String coef= "Coef"; //he so quy doi
  static const String attrGUID= "AttrGUID";
  static const String attrName= "AttrName";
  static const String listAttrDetails= "ListAttrDetails";
  static const String attrDetailGUID= "AttrDetailGUID";
  static const String attrVal= "AttrVal"; //ten thuoc tinh con
  static const String taxRateGUID= "TaxRateGUID"; //ma so thue
  static const String taxName= "TaxName";
  static const String taxRate= "TaxRate";
  static const String bankGUID= "BankGUID";
  static const String bankShortName= "BankShortName";
  static const String statusGUID= "StatusGUID";
  static const String statusName= "StatusName";
  static const String paymentStatusID= "PaymentStatusID";
  static const String paymentStatusName= "PaymentStatusName";
  static const String currencyID= "CurrencyID"; //id don vi tien te
  static const String currencyName= "CurrencyName"; //ten don vi tien te
  static const String discountRateGUID= "DiscountRateGUID";
  static const String discountName= "DiscountName";
  static const String discountRate= "DiscountRate";
  static const String paymentMethodGUID= "PaymentMethodGUID";
  static const String paymentMethodName= "PaymentMethodName";
  static const String paymentMethodTypeID= "PaymentMethodTypeID";
  static const String itemGUID= "ItemGUID";
  static const String sku= "SKU"; //ma mat hang
  static const String barcode= "Barcode";
  static const String itemName= "ItemName";
  static const String itemNameShow= "ItemNameShow";
  static const String currentQty= "CurrentQty"; //so luong hien tai
  static const String price= "Price"; //don gia
  static const String isActive= "IsActive"; //trang thai dang su dung
  static const String listImgs= "ListImgs"; //danh sach anh
  static const String listAttrs= "ListAttrs"; //danh sach thuoc tinh
  static const String listUnits= "ListUnits"; //danh sach don vi
  static const String listItemChilds= "ListItemChilds"; //danh sach itm con
  static const String objectCode= "ObjectCode"; //ma doi tac
  static const String avatarURL= "AvatarURL";
  static const String listAddress= "ListAddress";
  static const String listBanks= "ListBanks";
  static const String cateName= "CateName";
  static const String label= "Label";
  static const String fromRefDate= "FromRefDate";
  static const String toRefDate= "ToRefDate";
  static const String fromPaymentTermDate= "FromPaymentTermDate";
  static const String toPaymentTermDate= "ToPaymentTermDate";
  static const String aiObjectGUID= "AIObjectGUID";
  static const String listPaymentStatusID= "ListPaymentStatusID";
  static const String fromAmount= "FromAmount"; //tu gia tri
  static const String toAmount= "ToAmount";
  static const String invHeader= "InvHeader";
  static const String refGUID= "RefGUID";
  static const String refNo= "RefNo";
  static const String refDate= "RefDate";
  static const String hTaxRateGUID= "HTaxRateGUID";
  static const String hTaxRate= "HTaxRate";
  static const String sumTaxAmount= "SumTaxAmount";
  static const String hDiscountRateGUID= "HDiscountRateGUID";
  static const String hDiscountRate= "HDiscountRate";
  static const String discountAmount= "DiscountAmount";
  static const String sumDiscountAmount= "SumDiscountAmount";
  static const String sumItemAmount= "SumItemAmount";
  static const String sumPaymentAmount= "SumPaymentAmount";
  static const String listInvDetails= "ListInvDetails";
  static const String refItemDetGUID= "RefItemDetGUID";
  static const String qty= "Qty";
  static const String amount= "Amount"; //thanh tien
  static const String taxAmount= "TaxAmount";
  static const String listAttrDetailGUIDs= "ListAttrDetailGUIDs";
  static const String fromCurrentQty= "FromCurrentQty";
  static const String toCurrentQty= "ToCurrentQty";
  static const String fromPrice= "FromPrice";
  static const String toPrice= "ToPrice";
  static const String fromQty= "FromQty";
  static const String toQty= "ToQty";
  static const String totalRecord= "TotalRecord"; //tong so luong
  static const String totalAmount= "TotalAmount"; //tong gia tri
  static const String listObjClient= "ListObjClient";
  static const String sumAmount= "SumAmount";
  static const String paidAmount= "PaidAmount";
  static const String remainAmount= "RemainAmount";
  static const String id= "ID";
  static const String locationInfo= "LocationInfo";
  static const String paymentTermDate= "PaymentTermDate";
  static const String imgGUID= "ImgGUID";
  static const String imgURL= "ImgURL";
  static const String isMain= "IsMain";
  static const String info= "Info";
  static const String orgID= "OrgID";
  static const String userID= "UserID";
  static const String sumRemainAmount= "SumRemainAmount";
  static const String listORIRefs= "ListORIRefs"; //danh sach phieu ban hang
  static const String listPays= "ListPays";
  static const String paymentAmount= "PaymentAmount";
  static const String businessTypeID= "BusinessTypeID";
  static const String statusID= "StatusID";
  static const String objAddressGUID= "ObjAddressGUID";
  static const String objBankGUID= "ObjBankGUID";
  static const String bankOwner= "BankOwner";
  static const String avatar= "Avatar";
  static const String fileName= "FileName";
  static const String fileExtension= "FileExtension";
  static const String fileContent= "FileContent";
  static const String cost= "Cost";
  static const String balanceQty= "BalanceQty"; //chenh lech
  static const String oriRefItemDetGUID= "ORIRefItemDetGUID"; //chi tiet phieu goc
  static const String reportGUID= "ReportGUID";
  static const String filters= "Filters";
  static const String listFilters= "ListFilters";
  static const String dataTypeID= "DataTypeID";
  static const String reportGroupGUID= "ReportGroupGUID";
  static const String reportGroupName= "ReportGroupName";
  static const String reportName= "ReportName";
  static const String reportTypeID= "ReportTypeID";
  static const String filterCode= "FilterCode";
  static const String filterName= "FilterName";
  static const String filterTypeID= "FilterTypeID";
  static const String filterData= "FilterData";
  static const String filterDataID= "FilterDataID";
  static const String filterDataName= "FilterDataName";
  static const String fromDate= "FromDate";
  static const String toDate= "ToDate";
  static const String defaultVal= "DefaultVal";
  static const String chartForms= "ChartForms";
  static const String dataName= "DataName";
  static const String colorCode= "ColorCode";
  static const String chartTypeID= "ChartTypeID";
  static const String listVals= "ListVals";
  static const String xName= "XName"; //gia tri cot X
  static const String val= "Val"; //gia tri cot Y
  static const String tableForms= "TableForms";
  static const String gridForms= "GridForms"; //kieu luoi
  static const String revenue= "Revenue";
  static const String capitalMoney= "CapitalMoney";
  static const String moneyReturnTotal= "MoneyReturnTotal";
  static const String moneyReturn= "MoneyReturn";
  static const String moneySpend= "MoneySpend";
  static const String khTakeCost= "KHTakeCost";
  static const String nccSpendCost= "NCCSpendCost";
  static const String average= "Average";
  static const String saleNumber= "SaleNumber";
  static const String step= "Step";
  static const String orgType= "OrgType";
  static const String orgContactName= "OrgContactName";
  static const String orgMobilePhone= "OrgMobilePhone";
  static const String orgLogo= "OrgLogo";
  static const String orgAddress= "OrgAddress";
  static const String orgEmail= "OrgEmail";
  static const String orgTaxCode= "OrgTaxCode";
  static const String orgPhone= "OrgPhone";
  static const String orgWebsite= "OrgWebsite";
  static const String financialYearFrom= "FinancialYearFrom";
  static const String financialYearTo= "FinancialYearTo";
  static const String currency= "Currency";
  static const String dateFormat= "DateFormat";
  static const String dateFormatType= "DateFormatType";
  static const String numberFormatType= "NumberFormatType";
  static const String taxRateType= "TaxRateType";
  static const String discountType= "DiscountType";
  static const String isSingleStore= "IsSingleStore";
  static const String storeOutMethodID= "StoreOutMethodID";
  static const String isReportTax= "IsReportTax";
  static const String circulars= "Circulars";
  static const String taxDeclareMethod= "TaxDeclareMethod";
  static const String taxPeriod= "TaxPeriod";
  static const String isApprove= "IsApprove";
  static const String isStoreOutOverAllow= "IsStoreOutOverAllow";
  static const String logo= "Lo+go";
  static const String orgDetails= "OrgDetails";
  static const String object= "object";
  static const String userGUID= "UserGUID";
  static const String accessTokenExpire= "AccessTokenExpire";
  static const String isXuatKhoAm= "IsXuatKhoAm";
  static const String sortCol= "SortCol";
  static const String listStatusID= "ListStatusID";
  static const String commandObject= "CommandObject";
  static const String commandType= "CommandType";
  static const String listObjectGUID= "ListObjectGUID";
  static const String sumDebtAmount= "SumDebtAmount";
  static const String listBankAccounts= "ListBankAccounts";
  static const String paymentMethodCode= "PaymentMethodCode";
  static const String currentDebt= "CurrentDebt";
  static const String orgBankGUID= "OrgBankGUID";
  static const String prodAmount = "ProdAmount";
  static const String timeAmount = "TimeAmount";
  static const String bonusAmount = "BonusAmount";
  static const String bhxh = "BHXH";
  static const String bhtn = "BHTN";
  static const String bhyt = "BHYT";
  static const String ttncn = "TTNCN";
  static const String giamTru = "GiamTru";
  static const String realAmount = "RealAmount";
  static const String lstDetails = "LstDetails";
}